export const agentActionTypes = {
  //GET AGENT SECTION
  GET_AGENTS_START: 'GET_AGENTS_START',
  GET_AGENTS_END: 'GET_AGENTS_END',
  GET_AGENTS_SUCCESS: 'GET_AGENTS_SUCCESS',
  GET_AGENTS_FAILURE: 'GET_AGENTS_FAILURE',
  //GET ALL AGENT SECTION
  GET_ALL_AGENTS_START: 'GET_ALL_AGENTS_START',
  GET_ALL_AGENTS_END: 'GET_ALL_AGENTS_END',
  GET_ALL_AGENTS_SUCCESS: 'GET_ALL_AGENTS_SUCCESS',
  GET_ALL_AGENTS_FAILURE: 'GET_ALL_AGENTS_FAILURE',
  //GET AGENT SECTION
  GET_AGENT_START: 'GET_AGENT_START',
  GET_AGENT_END: 'GET_AGENT_END',
  GET_AGENT_SUCCESS: 'GET_AGENT_SUCCESS',
  GET_AGENT_FAILURE: 'GET_AGENT_FAILURE',
  //CREATE AGENT SECTION
  CREATE_AGENT_START: 'CREATE_AGENT_START',
  CREATE_AGENT_END: 'CREATE_AGENT_END',
  CREATE_AGENT_SUCCESS: 'CREATE_AGENT_SUCCESS',
  CREATE_AGENT_FAILURE: 'CREATE_AGENT_FAILURE',
  //EDIT AGENT SECTION
  EDIT_AGENT_START: 'EDIT_AGENT_START',
  EDIT_AGENT_END: 'EDIT_AGENT_END',
  EDIT_AGENT_SUCCESS: 'EDIT_AGENT_SUCCESS',
  EDIT_AGENT_FAILURE: 'EDIT_AGENT_FAILURE',
  //DELETE AGENT SECTION
  DELETE_AGENT_START: 'DELETE_AGENT_START',
  DELETE_AGENT_END: 'DELETE_AGENT_END',
  DELETE_AGENT_SUCCESS: 'DELETE_AGENT_SUCCESS',
  DELETE_AGENT_FAILURE: 'DELETE_AGENT_FAILURE'
};
