export const hospitalActionTypes = {
  //GET HOSPITAL SECTION
  GET_HOSPITALS_START: 'GET_HOSPITALS_START',
  GET_HOSPITALS_END: 'GET_HOSPITALS_END',
  GET_HOSPITALS_SUCCESS: 'GET_HOSPITALS_SUCCESS',
  GET_HOSPITALS_FAILURE: 'GET_HOSPITALS_FAILURE',
  //GET ALL HOSPITAL SECTION
  GET_ALL_HOSPITALS_START: 'GET_ALL_HOSPITALS_START',
  GET_ALL_HOSPITALS_END: 'GET_ALL_HOSPITALS_END',
  GET_ALL_HOSPITALS_SUCCESS: 'GET_ALL_HOSPITALS_SUCCESS',
  GET_ALL_HOSPITALS_FAILURE: 'GET_ALL_HOSPITALS_FAILURE',
  //GET HOSPITAL SECTION
  GET_HOSPITAL_START: 'GET_HOSPITAL_START',
  GET_HOSPITAL_END: 'GET_HOSPITAL_END',
  GET_HOSPITAL_SUCCESS: 'GET_HOSPITAL_SUCCESS',
  GET_HOSPITAL_FAILURE: 'GET_HOSPITAL_FAILURE',
  //CREATE HOSPITAL SECTION
  CREATE_HOSPITAL_START: 'CREATE_HOSPITAL_START',
  CREATE_HOSPITAL_END: 'CREATE_HOSPITAL_END',
  CREATE_HOSPITAL_SUCCESS: 'CREATE_HOSPITAL_SUCCESS',
  CREATE_HOSPITAL_FAILURE: 'CREATE_HOSPITAL_FAILURE',
  //EDIT HOSPITAL SECTION
  EDIT_HOSPITAL_START: 'EDIT_HOSPITAL_START',
  EDIT_HOSPITAL_END: 'EDIT_HOSPITAL_END',
  EDIT_HOSPITAL_SUCCESS: 'EDIT_HOSPITAL_SUCCESS',
  EDIT_HOSPITAL_FAILURE: 'EDIT_HOSPITAL_FAILURE',
  //DELETE HOSPITAL SECTION
  DELETE_HOSPITAL_START: 'DELETE_HOSPITAL_START',
  DELETE_HOSPITAL_END: 'DELETE_HOSPITAL_END',
  DELETE_HOSPITAL_SUCCESS: 'DELETE_HOSPITAL_SUCCESS',
  DELETE_HOSPITAL_FAILURE: 'DELETE_HOSPITAL_FAILURE'
};
