export const organisationActionTypes = {
  //GET ORGANISATION SECTION
  GET_ORGANISATIONS_START: 'GET_ORGANISATIONS_START',
  GET_ORGANISATIONS_END: 'GET_ORGANISATIONS_END',
  GET_ORGANISATIONS_SUCCESS: 'GET_ORGANISATIONS_SUCCESS',
  GET_ORGANISATIONS_FAILURE: 'GET_ORGANISATIONS_FAILURE',
  //GET ALL ORGANISATION SECTION
  GET_ALL_ORGANISATIONS_START: 'GET_ALL_ORGANISATIONS_START',
  GET_ALL_ORGANISATIONS_END: 'GET_ALL_ORGANISATIONS_END',
  GET_ALL_ORGANISATIONS_SUCCESS: 'GET_ALL_ORGANISATIONS_SUCCESS',
  GET_ALL_ORGANISATIONS_FAILURE: 'GET_ALL_ORGANISATIONS_FAILURE',
  //GET ORGANISATION SECTION
  GET_ORGANISATION_START: 'GET_ORGANISATION_START',
  GET_ORGANISATION_END: 'GET_ORGANISATION_END',
  GET_ORGANISATION_SUCCESS: 'GET_ORGANISATION_SUCCESS',
  GET_ORGANISATION_FAILURE: 'GET_ORGANISATION_FAILURE',
  //CREATE ORGANISATION SECTION
  CREATE_ORGANISATION_START: 'CREATE_ORGANISATION_START',
  CREATE_ORGANISATION_END: 'CREATE_ORGANISATION_END',
  CREATE_ORGANISATION_SUCCESS: 'CREATE_ORGANISATION_SUCCESS',
  CREATE_ORGANISATION_FAILURE: 'CREATE_ORGANISATION_FAILURE',
  //EDIT ORGANISATION SECTION
  EDIT_ORGANISATION_START: 'EDIT_ORGANISATION_START',
  EDIT_ORGANISATION_END: 'EDIT_ORGANISATION_END',
  EDIT_ORGANISATION_SUCCESS: 'EDIT_ORGANISATION_SUCCESS',
  EDIT_ORGANISATION_FAILURE: 'EDIT_ORGANISATION_FAILURE',
  //DELETE ORGANISATION SECTION
  DELETE_ORGANISATION_START: 'DELETE_ORGANISATION_START',
  DELETE_ORGANISATION_END: 'DELETE_ORGANISATION_END',
  DELETE_ORGANISATION_SUCCESS: 'DELETE_ORGANISATION_SUCCESS',
  DELETE_ORGANISATION_FAILURE: 'DELETE_ORGANISATION_FAILURE',
  //CREATE ORGANISATION AGENT SECTION
  CREATE_ORGANISATION_AGENT_START: 'CREATE_ORGANISATION_AGENT_START',
  CREATE_ORGANISATION_AGENT_END: 'CREATE_ORGANISATION_AGENT_END',
  CREATE_ORGANISATION_AGENT_SUCCESS: 'CREATE_ORGANISATION_AGENT_SUCCESS',
  CREATE_ORGANISATION_AGENT_FAILURE: 'CREATE_ORGANISATION_AGENT_FAILURE'
};
