export const vaccineeActionTypes = {
  //GET ADMIN SECTION
  GET_VACCINEES_START: 'GET_VACCINEES_START',
  GET_VACCINEES_END: 'GET_VACCINEES_END',
  GET_VACCINEES_SUCCESS: 'GET_VACCINEES_SUCCESS',
  GET_VACCINEES_FAILURE: 'GET_VACCINEES_FAILURE',
  //CREATE ADMIN SECTION
  CREATE_VACCINEE_START: 'CREATE_VACCINEE_START',
  CREATE_VACCINEE_END: 'CREATE_VACCINEE_END',
  CREATE_VACCINEE_SUCCESS: 'CREATE_VACCINEE_SUCCESS',
  CREATE_VACCINEE_FAILURE: 'CREATE_VACCINEE_FAILURE'
};
